### ISSUE TITLE
Syntax Issues

### ISSUE THREAD

**Issue by TrueCyberAxe** [hassenius/hcl2mdtable#1]
the print statements need to have brackets print(blah) instead of print blah

**Comment by hassenius** [comment]
Ah, yeah, I haven't used this one in a very long time... I would have used python 2.7 at the time, some amount of porting is probably required...
I'd appreciate a PR if you want to look at it..

**Comment by TrueCyberAxe** [comment]
> Ah, yeah, I haven't used this one in a very long time... I would have used python 2.7 at the time, some amount of porting is probably required...
> I'd appreciate a PR if you want to look at it..

Working on it now i'll stick in a pr when done

**Comment by hassenius** [comment]
Thanks @TrueCyberAxe 
I think you've fixed this via #3
