### ISSUE TITLE
KeyError: variable

### ISSUE THREAD

**Issue by TrueCyberAxe** [hassenius/hcl2mdtable#2]
after fixing the print statements the following error occurs

`| variable           | default       |required| description                            |
|--------------------|---------------|--------|----------------------------------------|
Traceback (most recent call last):
  File "/Users/censored/Scripts/python/hcl2mdt.py", line 11, in <module>
    for key in obj['variable'].keys():
KeyError: 'variable'`

**Comment by hassenius** [comment]
Ah, yeah, I haven't used this one in a very long time... I would have used python 2.7 at the time, some amount of porting is probably required...
I'd appreciate a PR if you want to look at it..

**Comment by hassenius** [comment]
Thanks @TrueCyberAxe 
I think you've fixed this via #3
